insert into pais values ('Afganistán','AF')
insert into pais values ('Albania','AL')
insert into pais values ('Alemania','DE')
insert into pais values ('Andorra','AD')
insert into pais values ('Angola','AO')
insert into pais values ('Anguila','AI')
insert into pais values ('Antártida','AQ')
insert into pais values ('Antigua y Barbuda','AG')
insert into pais values ('Arabia Saudita','SA')
insert into pais values ('Argelia','DZ')
insert into pais values ('Argentina','AR')
insert into pais values ('Armenia','AM')
insert into pais values ('Aruba','AW')
insert into pais values ('Australia','AU')
insert into pais values ('Austria','AT')
insert into pais values ('Azerbaiyán','AZ')
insert into pais values ('Bahamas','BS')
insert into pais values ('Bangladés','BD')
insert into pais values ('Barbados','BB')
insert into pais values ('Baréin','BH')
insert into pais values ('Bélgica','BE')
insert into pais values ('Belice','BZ')
insert into pais values ('Benín','BJ')
insert into pais values ('Bermudas','BM')
insert into pais values ('Bielorrusia','BY')
insert into pais values ('Bolivia, Estado Plurinacional de','BO')
insert into pais values ('Bonaire, San Eustaquio y Saba','BQ')
insert into pais values ('Bosnia y Herzegovina','BA')
insert into pais values ('Botsuana','BW')
insert into pais values ('Brasil','BR')
insert into pais values ('Brunéi Darussalam','BN')
insert into pais values ('Bulgaria','BG')
insert into pais values ('Burkina Faso','BF')
insert into pais values ('Burundi','BI')
insert into pais values ('Bután','BT')
insert into pais values ('Cabo Verde','CV')
insert into pais values ('Camboya','KH')
insert into pais values ('Camerún','CM')
insert into pais values ('Canadá','CA')
insert into pais values ('Chad','TD')
insert into pais values ('Chile','CL')
insert into pais values ('China, República Popular','CN')
insert into pais values ('Chipre','CY')
insert into pais values ('Colombia','CO')
insert into pais values ('Comoras','KM')
insert into pais values ('Congo, La República Democrática del','CD')
insert into pais values ('Congo','CG')
insert into pais values ('Corea, República de','KR')
insert into pais values ('Corea, República Democrática Popular de','KP')
insert into pais values ('Costa de Marfil','CI')
insert into pais values ('Costa Rica','CR')
insert into pais values ('Croacia','HR')
insert into pais values ('Cuba','CU')
insert into pais values ('Curazao','CW')
insert into pais values ('Dinamarca','DK')
insert into pais values ('Dominica','DM')
insert into pais values ('Ecuador','EC')
insert into pais values ('Egipto','EG')
insert into pais values ('El Salvador','SV')
insert into pais values ('Emiratos Árabes Unidos','AE')
insert into pais values ('Eritrea','ER')
insert into pais values ('Eslovaquia','SK')
insert into pais values ('Eslovenia','SI')
insert into pais values ('España','ES')
insert into pais values ('Estados Unidos','US')
insert into pais values ('Estonia','EE')
insert into pais values ('Etiopía','ET')
insert into pais values ('Federacion Rusa','RU')
insert into pais values ('Filipinas','PH')
insert into pais values ('Finlandia','FI')
insert into pais values ('Fiyi','FJ')
insert into pais values ('Francia','FR')
insert into pais values ('Gabón','GA')
insert into pais values ('Gambia','GM')
insert into pais values ('Georgia','GE')
insert into pais values ('Ghana','GH')
insert into pais values ('Gibraltar','GI')
insert into pais values ('Granada','GD')
insert into pais values ('Grecia','GR')
insert into pais values ('Groenlandia','GL')
insert into pais values ('Guadalupe','GP')
insert into pais values ('Guam','GU')
insert into pais values ('Guatemala','GT')
insert into pais values ('Guayana Francesa','GF')
insert into pais values ('Guernsey','GG')
insert into pais values ('Guinea-Bisáu','GW')
insert into pais values ('Guinea Ecuatorial','GQ')
insert into pais values ('Guinea','GN')
insert into pais values ('Guyana','GY')
insert into pais values ('Haití','HT')
insert into pais values ('Honduras','HN')
insert into pais values ('Hong Kong','HK')
insert into pais values ('Hungría','HU')
insert into pais values ('India','IN')
insert into pais values ('Indonesia','ID')
insert into pais values ('Irak','IQ')
insert into pais values ('Irán, República Islámica de','IR')
insert into pais values ('Irlanda','IE')
insert into pais values ('Isla Bouvet','BV')
insert into pais values ('Isla de Man','IM')
insert into pais values ('Isla de Navidad','CX')
insert into pais values ('Isla Norfolk','NF')
insert into pais values ('Islandia','IS')
insert into pais values ('Islas Åland','AX')
insert into pais values ('Islas Caimán','KY')
insert into pais values ('Islas Cocos (Keeling)','CC')
insert into pais values ('Islas Cook','CK')
insert into pais values ('Islas Falkland (Malvinas)','FK')
insert into pais values ('Islas Feroe','FO')
insert into pais values ('Islas Georgias del Sur y Sandwich del Sur','GS')
insert into pais values ('Islas Heard y Mcdonald','HM')
insert into pais values ('Islas Marianas del Norte','MP')
insert into pais values ('Islas Marshall','MH')
insert into pais values ('Islas Salomón','SB')
insert into pais values ('Islas Turcas y Caicos','TC')
insert into pais values ('Islas Ultramarinas Menores de Estados Unidos','UM')
insert into pais values ('Islas Virgenes Británicas','VG')
insert into pais values ('Islas Virgenes de Los Estados Unidos','VI')
insert into pais values ('Israel','IL')
insert into pais values ('Italia','IT')
insert into pais values ('Jamaica','JM')
insert into pais values ('Japón','JP')
insert into pais values ('Jersey','JE')
insert into pais values ('Jordania','JO')
insert into pais values ('Kazajistán','KZ')
insert into pais values ('Kenia','KE')
insert into pais values ('Kirguistán','KG')
insert into pais values ('Kiribati','KI')
insert into pais values ('Kuwait','KW')
insert into pais values ('Lesoto','LS')
insert into pais values ('Letonia','LV')
insert into pais values ('Líbano','LB')
insert into pais values ('Liberia','LR')
insert into pais values ('Libia','LY')
insert into pais values ('Liechtenstein','LI')
insert into pais values ('Lituania','LT')
insert into pais values ('Luxemburgo','LU')
insert into pais values ('Macao','MO')
insert into pais values ('Macedonia, La Antigua República Yugoslava de','MK')
insert into pais values ('Madagascar','MG')
insert into pais values ('Malasia','MY')
insert into pais values ('Malaui','MW')
insert into pais values ('Maldivas','MV')
insert into pais values ('Malí','ML')
insert into pais values ('Malta','MT')
insert into pais values ('Marruecos','MA')
insert into pais values ('Martinica','MQ')
insert into pais values ('Mauricio','MU')
insert into pais values ('Mauritania','MR')
insert into pais values ('Mayotte','YT')
insert into pais values ('México','MX')
insert into pais values ('Micronesia, Estados Federados de','FM')
insert into pais values ('Moldavia, República de','MD')
insert into pais values ('Mónaco','MC')
insert into pais values ('Mongolia','MN')
insert into pais values ('Montenegro','ME')
insert into pais values ('Montserrat','MS')
insert into pais values ('Mozambique','MZ')
insert into pais values ('Myanmar','MM')
insert into pais values ('Nabimia','NA')
insert into pais values ('Nauru','NR')
insert into pais values ('Nepal','NP')
insert into pais values ('Nicaragua','NI')
insert into pais values ('Nigeria','NG')
insert into pais values ('Níger','NE')
insert into pais values ('Niue','NU')
insert into pais values ('Noruega','NO')
insert into pais values ('Nueva Caledonia','NC')
insert into pais values ('Nueva Zelanda','NZ')
insert into pais values ('Omán','OM')
insert into pais values ('Países Bajos','NL')
insert into pais values ('Pakistán','PK')
insert into pais values ('Palaos','PW')
insert into pais values ('Palestina, Estado de','PS')
insert into pais values ('Panamá','PA')
insert into pais values ('Papúa Nueva Guinea','PG')
insert into pais values ('Paraguay','PY')
insert into pais values ('Perú','PE')
insert into pais values ('Pitcairn','PN')
insert into pais values ('Polinesia Francesa','PF')
insert into pais values ('Polonia','PL')
insert into pais values ('Portugal','PT')
insert into pais values ('Puerto Rico','PR')
insert into pais values ('Qatar','QA')
insert into pais values ('Reino Unido','GB')
insert into pais values ('República Centroafricana','CF')
insert into pais values ('República Checa','CZ')
insert into pais values ('República Democrática Popular Lao','LA')
insert into pais values ('República Dominicana','DO')
insert into pais values ('Reunión','RE')
insert into pais values ('Ruanda','RW')
insert into pais values ('Rumania','RO')
insert into pais values ('Sahara Occidental','EH')
insert into pais values ('Samoa Americana','AS')
insert into pais values ('Samoa','WS')
insert into pais values ('San Bartolomé','BL')
insert into pais values ('San Cristóbal y Nieves','KN')
insert into pais values ('San Marino','SM')
insert into pais values ('San Martín (Parte Francesa)','MF')
insert into pais values ('San Pedro y Miquelón','PM')
insert into pais values ('San Vicente y Las Granadinas','VC')
insert into pais values ('Santa Helena, Ascensión y Tristán de Acuña','SH')
insert into pais values ('Santa Lucía','LC')
insert into pais values ('Santa Sede (Ciudad Estado Vaticano)','VA')
insert into pais values ('Santo Tomé y Principe','ST')
insert into pais values ('Senegal','SN')
insert into pais values ('Serbia','RS')
insert into pais values ('Seychelles','SC')
insert into pais values ('Sierra Leona','SL')
insert into pais values ('Singapur','SG')
insert into pais values ('Sint Maarten (Parte Neerlandesa)','SX')
insert into pais values ('Siria, República Arabe de','SY')
insert into pais values ('Somalia','SO')
insert into pais values ('Sri Lanka','LK')
insert into pais values ('Suazilandia','SZ')
insert into pais values ('Sudáfrica','ZA')
insert into pais values ('Sudán del Sur','SS')
insert into pais values ('Sudán','SD')
insert into pais values ('Suecia','SE')
insert into pais values ('Suiza','CH')
insert into pais values ('Surinam','SR')
insert into pais values ('Svalbard y Jan Mayen','SJ')
insert into pais values ('Tailandia','TH')
insert into pais values ('Taiwán, Provincia de China','TW')
insert into pais values ('Tanzania, República Unida de','TZ')
insert into pais values ('Tayikistán','TJ')
insert into pais values ('Territorio Británico del Océano Índico','IO')
insert into pais values ('Territorios Australes Franceses','TF')
insert into pais values ('Timor-Leste','TL')
insert into pais values ('Togo','TG')
insert into pais values ('Tokelau','TK')
insert into pais values ('Tonga','TO')
insert into pais values ('Trinidad y Tobago','TT')
insert into pais values ('Túnez','TN')
insert into pais values ('Turkmenistán','TM')
insert into pais values ('Turquía','TR')
insert into pais values ('Tuvalu','TV')
insert into pais values ('Ucrania','UA')
insert into pais values ('Uganda','UG')
insert into pais values ('Uruguay','UY')
insert into pais values ('Uzbekistán','UZ')
insert into pais values ('Vanuatu','VU')
insert into pais values ('Venezuela, República Bolivariana de','VE')
insert into pais values ('Viet Nam','VN')
insert into pais values ('Wallis y Futuna','WF')
insert into pais values ('Yemen','YE')
insert into pais values ('Yibuti','DJ')
insert into pais values ('Zambia','ZM')
insert into pais values ('Zimbabue','ZW')
